(()=>{
const scenarios={
legal:{title:'Legal workflow copilot',summary:'Assist research, drafting, and matter preparation while preserving attorney judgment and source traceability.',status:'SHAPE',values:{outcome:88,legal:82,risk:68,data:55,authority:92,owner:58,evidence:61},decision:'Shape the use case before funding: define privileged-data boundaries, named product ownership, and minimum evaluation evidence.',authority:'Attorneys retain substantive judgment, approval, and accountability; AI prepares and surfaces evidence.'},
compliance:{title:'Compliance signal monitoring',summary:'Prioritize potentially meaningful patterns for review without treating a model signal as a compliance conclusion.',status:'FUND',values:{outcome:90,legal:88,risk:78,data:82,authority:91,owner:86,evidence:84},decision:'Fund a controlled release with calibrated thresholds, traceable alerts, named review ownership, and monitored false-positive burden.',authority:'Compliance professionals determine significance, action, and escalation; the system ranks and explains signals.'},
investigation:{title:'Investigation summarization',summary:'Organize sensitive matter records and chronology while preserving confidentiality, evidentiary integrity, and investigator control.',status:'HOLD',values:{outcome:74,legal:62,risk:42,data:35,authority:84,owner:70,evidence:48},decision:'Hold pending stronger data segregation, access control, validation, retention, and evidence-integrity design.',authority:'Investigators retain fact finding, credibility assessment, conclusions, and case decisions.'},
security:{title:'Security incident triage',summary:'Summarize and route incident evidence to reduce response friction without allowing autonomous containment beyond approved boundaries.',status:'SHAPE',values:{outcome:93,legal:80,risk:59,data:72,authority:76,owner:88,evidence:67},decision:'Shape the release around explicit action boundaries, confidence thresholds, fallback, logging, and after-action review.',authority:'Security leaders retain containment and business-impact decisions; automation may classify and route within approved limits.'}}
const buttons=[...document.querySelectorAll('.scenario-button')], bars=[...document.querySelectorAll('.contract-bar')];
function render(key){const s=scenarios[key]; if(!s)return; document.querySelector('#scenario-title').textContent=s.title;document.querySelector('#scenario-summary').textContent=s.summary;document.querySelector('#contract-status').textContent=s.status;document.querySelector('#decision-text').textContent=s.decision;document.querySelector('#authority-text').textContent=s.authority;buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===key)));bars.forEach(b=>{const v=s.values[b.dataset.dimension];b.style.setProperty('--height',v+'%');b.classList.toggle('weak',v<50);b.classList.toggle('watch',v>=50&&v<70)});const avg=Object.values(s.values).reduce((a,b)=>a+b,0)/7;document.querySelector('.contract-scan').style.top=(100-avg*.75)+'%';}
buttons.forEach(b=>b.addEventListener('click',()=>render(b.dataset.scenario)));document.querySelector('.reset-button')?.addEventListener('click',()=>render('legal'));
document.querySelector('.nav-toggle')?.addEventListener('click',e=>{const nav=document.querySelector('#site-nav');const open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open));});render('legal');

})();
